In [6]:
d1="It is going to rain today"
d2="Today I am not going outside"
d3="I am going to watch the season premiere"

l1=d1.split()
l2=d2.split()
l3=d3.split()
val1=set(l1+l2+l3)
val1

{'I',
 'It',
 'Today',
 'am',
 'going',
 'is',
 'not',
 'outside',
 'premiere',
 'rain',
 'season',
 'the',
 'to',
 'today',
 'watch'}

In [4]:
dict1={}
for i in val1:
    if i in d1:
        dict1[i]=round(1/len(l1),2)
    else:
        dict1[i]=0

dict1

{'is': 0.17,
 'season': 0,
 'today': 0.17,
 'premiere': 0,
 'It': 0.17,
 'not': 0,
 'outside': 0,
 'going': 0.17,
 'the': 0,
 'Today': 0,
 'watch': 0,
 'rain': 0.17,
 'to': 0.17,
 'I': 0.17,
 'am': 0}

In [10]:
dict2={}
for i in val1:
    if i in d1:
        dict2[i]=round(1/len(l2),2)
    else:
        dict2[i]=0
dict2

{'is': 0.17,
 'season': 0,
 'today': 0.17,
 'premiere': 0,
 'It': 0.17,
 'not': 0,
 'outside': 0,
 'going': 0.17,
 'the': 0,
 'Today': 0,
 'watch': 0,
 'rain': 0.17,
 'to': 0.17,
 'I': 0.17,
 'am': 0}

In [12]:
dict3={}
for i in val1:
    if i in d1:
       dict3[i] =round(1/len(l3),2)
    else:
        dict3[i]=0

dict3

{'is': 0.12,
 'season': 0,
 'today': 0.12,
 'premiere': 0,
 'It': 0.12,
 'not': 0,
 'outside': 0,
 'going': 0.12,
 'the': 0,
 'Today': 0,
 'watch': 0,
 'rain': 0.12,
 'to': 0.12,
 'I': 0.12,
 'am': 0}

In [14]:
import pandas as pd
df1=pd.DataFrame(dict1,index=['A'])
df2=pd.DataFrame(dict2,index=['B'])
df3=pd.DataFrame(dict3,index=['C'])
df1,df2,df3

(     is  season  today  premiere    It  not  outside  going  the  Today  \
 A  0.17       0   0.17         0  0.17    0        0   0.17    0      0   
 
    watch  rain    to     I  am  
 A      0  0.17  0.17  0.17   0  ,
      is  season  today  premiere    It  not  outside  going  the  Today  \
 B  0.17       0   0.17         0  0.17    0        0   0.17    0      0   
 
    watch  rain    to     I  am  
 B      0  0.17  0.17  0.17   0  ,
      is  season  today  premiere    It  not  outside  going  the  Today  \
 C  0.12       0   0.12         0  0.12    0        0   0.12    0      0   
 
    watch  rain    to     I  am  
 C      0  0.12  0.12  0.12   0  )

In [36]:
df1

is  season  today  premiere    It  not  outside  going  the  Today  \
A  0.17       0   0.17         0  0.17    0        0   0.17    0      0   

   watch  rain    to     I  am  
A      0  0.17  0.17  0.17   0

In [40]:
df2

is  season  today  premiere    It  not  outside  going  the  Today  \
B  0.17       0   0.17         0  0.17    0        0   0.17    0      0   

   watch  rain    to     I  am  
B      0  0.17  0.17  0.17   0

In [42]:
df3

is  season  today  premiere    It  not  outside  going  the  Today  \
C  0.12       0   0.12         0  0.12    0        0   0.12    0      0   

   watch  rain    to     I  am  
C      0  0.12  0.12  0.12   0

TfidfVectorizer

In [49]:
Document1= "going rain today."
Document2= "Today going outside."
Document3= "going watch season premiere."
Doc = [Document1 ,Document2 , Document3]
print(Doc)

['going rain today.', 'Today going outside.', 'going watch season premiere.']


In [51]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer=TfidfVectorizer()
x=vectorizer.fit_transform(Doc)

In [53]:
vectorizer.vocabulary_

{'going': 0,
 'rain': 3,
 'today': 5,
 'outside': 1,
 'watch': 6,
 'season': 4,
 'premiere': 2}

In [55]:
analyze=vectorizer.build_analyzer()
print('Document 1',analyze(Document1))
print('Document 2',analyze(Document2))
print('Document 3',analyze(Document3))
print('Document transform',x.toarray())

Document 1 ['going', 'rain', 'today']
Document 2 ['today', 'going', 'outside']
Document 3 ['going', 'watch', 'season', 'premiere']
Document transform [[0.42544054 0.         0.         0.72033345 0.         0.54783215
  0.        ]
 [0.42544054 0.72033345 0.         0.         0.         0.54783215
  0.        ]
 [0.32274454 0.         0.54645401 0.         0.54645401 0.
  0.54645401]]


In [57]:
vectorizer.get_feature_names_out()

array(['going', 'outside', 'premiere', 'rain', 'season', 'today', 'watch'],
      dtype=object)

In [59]:
len(x.toarray()[0])

7

In [61]:
x.toarray()[0]

array([0.42544054, 0.        , 0.        , 0.72033345, 0.        ,
       0.54783215, 0.        ])

In [63]:
#without Normalization
docuemnt1='good movie.'
document2='good snacks.'
document3='movie snacks good.'
doc=[docuemnt1,document2,document3]
print(doc)

from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer=TfidfVectorizer(norm=None)
x=vectorizer.fit_transform(doc)

analyze=vectorizer.build_analyzer()
print('document 1',analyze(docuemnt1))
print('document 2',analyze(document2))
print('document 3',analyze(document3))

vectorizer.get_feature_names_out()

['good movie.', 'good snacks.', 'movie snacks good.']
document 1 ['good', 'movie']
document 2 ['good', 'snacks']
document 3 ['movie', 'snacks', 'good']


array(['good', 'movie', 'snacks'], dtype=object)

In [65]:
v1=[0.61335554,0.78980693,0]
np.linalg.norm(v1)

np.float64(1.0000000025623583)

In [67]:
1 * (np.log((3 + 1)/(3+1)) + 1)

np.float64(1.0)

In [69]:
# movie 
1 * (np.log((3 + 1)/(2+1)) + 1)

np.float64(1.2876820724517808)

In [ ]:
# With Normalization
doc

In [71]:
# With Normalization
Document1= "good movie."
Document2= "good snacks."
Document3= "movie snacks good."
Doc = [Document1 ,Document2 , Document3]
print(Doc)


from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(Doc)

analyze = vectorizer.build_analyzer()
print("Document 1",analyze(Document1))
print("Document 2",analyze(Document2))
print("Document 3",analyze(Document3))
print("Document transform",X.toarray())

vectorizer.get_feature_names_out()

['good movie.', 'good snacks.', 'movie snacks good.']
Document 1 ['good', 'movie']
Document 2 ['good', 'snacks']
Document 3 ['movie', 'snacks', 'good']
Document transform [[0.61335554 0.78980693 0.        ]
 [0.61335554 0.         0.78980693]
 [0.48133417 0.61980538 0.61980538]]


array(['good', 'movie', 'snacks'], dtype=object)

In [73]:
tfidf_vector =[1,1.28768207,0]
tfidf_vector=tfidf_vector/np.linalg.norm(tfidf_vector)
print(tfidf_vector)

[0.61335554 0.78980693 0.        ]
