In [3]:
from nltk.corpus import stopwords
sentences = ['sky is nice', 'clouds are nice', 'Sky is nice and Clouds are nice']
cleaned_sentence=[]
for sentence in sentences:
    word=sentence.lower()
    word=word.split()

    word=[i for i in word if i not in set(stopwords.words('english'))]
    word=" ".join(word)
    cleaned_sentence.append(word)
print(cleaned_sentence)

['sky nice', 'clouds nice', 'sky nice clouds nice']


In [4]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=3)
Bagofwords=cv.fit_transform(cleaned_sentence)
Bagofwords.toarray()

array([[0, 1, 1],
       [1, 1, 0],
       [1, 2, 1]])

In [5]:
import pandas as pd 
pd.DataFrame(Bagofwords.toarray(),columns=['cloud','nice','sky'])

cloud  nice  sky
0      0     1    1
1      1     1    0
2      1     2    1

In [6]:
cv.vocabulary_

{'sky': np.int64(2), 'nice': np.int64(1), 'clouds': np.int64(0)}

In [7]:
#Bagofwords.view()

In [8]:
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import CountVectorizer
sentences = ['Game of Thrones is an amazing tv series!', 
             'Game of Thrones is the best tv series!', 
             'Game of Thrones is so great']
cleaned_sentences=[]

for sentence in sentences:
    word=sentence.lower()
    word= word.split()
    word=[i for i in word if i not in set(stopwords.words('english'))]
    word=" ".join(word)
    cleaned_sentences.append(word)

print(cleaned_sentences)
cv=CountVectorizer()
Bagofwords=cv.fit_transform(cleaned_sentences).toarray()
print(cv.vocabulary_)
print(Bagofwords)

['game thrones amazing tv series!', 'game thrones best tv series!', 'game thrones great']
{'game': 2, 'thrones': 5, 'amazing': 0, 'tv': 6, 'series': 4, 'best': 1, 'great': 3}
[[1 0 1 0 1 1 1]
 [0 1 1 0 1 1 1]
 [0 0 1 1 0 1 0]]


In [9]:
sorted(list(cv.vocabulary_.keys()))

['amazing', 'best', 'game', 'great', 'series', 'thrones', 'tv']

In [17]:
cv.vocabulary_

{'game': 2,
 'thrones': 5,
 'amazing': 0,
 'tv': 6,
 'series': 4,
 'best': 1,
 'great': 3}

In [19]:
sen=' '.join(cleaned_sentence)
l=list(set(sen.split()))
print("vocabulary:",l)
d={}
l1=[]
for sentence in cleaned_sentence:
    for i in l:
        if i in sentence:
            d[i]=1
        else:
            d[i]=0
    mykeys=list(d.keys())
    mykeys.sort()
    sorted_dict={i: d[i] for i in mykeys}
    l1.append(sorted_dict)

print(l1)
l2=[i.values() for i in l1]
l2

vocabulary: ['nice', 'clouds', 'sky']
[{'clouds': 0, 'nice': 1, 'sky': 1}, {'clouds': 1, 'nice': 1, 'sky': 0}, {'clouds': 1, 'nice': 1, 'sky': 1}]


[dict_values([0, 1, 1]), dict_values([1, 1, 0]), dict_values([1, 1, 1])]

In [21]:
import nltk
word2count={}
for data in sentences:
    words=nltk.word_tokenize(data)
    for word in words:
        if word not in word2count.keys():
            word2count[word]=1
        else:
            word2count[word]+=1
print(word2count)

{'Game': 3, 'of': 3, 'Thrones': 3, 'is': 3, 'an': 1, 'amazing': 1, 'tv': 2, 'series': 2, '!': 2, 'the': 1, 'best': 1, 'so': 1, 'great': 1}
